# Generated by Django 2.0.7 on 2021-03-28 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='summary',
            field=models.TextField(default='this is cool!'),
        ),
    ]
