# Generated by Django 2.0.7 on 2021-03-28 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_project_summary'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project',
            new_name='Product',
        ),
    ]
